{{- if .Values.execWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildfarm.fullname" . }}-exec-worker
  labels:
    name: {{ include "buildfarm.fullname" . }}-exec-worker
    {{- include "buildfarm.labels" . | nindent 4 }}
  {{- with .Values.execWorker.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.execWorker.service.type }}
  ports:
    - port: {{ .Values.execWorker.service.port }}
      targetPort: worker-comm
      protocol: TCP
      name: gprc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    name: {{ include "buildfarm.fullname" . }}-exec-worker
    {{- include "buildfarm.selectorLabels" . | nindent 4 }}
{{- end }}
