#!/bin/bash

set -e
# This is a drop-in replacement for cgexec, with the following differences:
#
# - It will put child processes in a cgroup relative to THIS cgroup's parent.

# Required arguments:
# -g <controllers>:<CgroupName>

# Function to display usage information
usage() {
    echo "Usage: $0 -g <value>" >&2
    exit 1
}

# Parse command line arguments
while getopts ":g:" opt; do
  case ${opt} in
    g )
      # Split the value on ":" and assign to variables
      IFS=':' read -r -a parts <<< "$OPTARG"
      controllers="${parts[0]}"
      cgroupName="${parts[1]}"
      ;;
    \? )
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# Check if both variables are set, otherwise show an error message and exit
if [ -z "$controllers" ] || [ -z "$cgroupName" ]; then
    echo "Error: Both controllers and cgroupName must be specified." >&2
    usage
fi

# Get my own Cgroup from /proc/self/cgroup.
# There are three fields here, separated by ':':
# - the group ID. This is always 0 for cgroups v2.
# - the enabled controllers. This is always empty for cgroups v2.
# - the cgroup Path. This is the only part we care about.
cgroupNameRelativePath="$(cut -d':' -f3- < /proc/self/cgroup)"

# This diverges from `cgexec` where we place ourselves in a group relative to parent.
# Example:
# cgroupName = `executions/operations/29aec796-ad19-4e6b-a83b-b8b9f55d0abb`
# This process starts in the ${cgroupNameRelativePath} cgroup:
#   ├─${baseCgroup}
#   │ ├─${cgroupNameRelativePath}
#   │ │ ├─123456 /tini -- java -jar /app/build_buildfarm/buildfarm-shard-worker_deploy.jar
#   │ │ └─123457 java -jar /app/build_buildfarm/buildfarm-shard-worker_deploy.jar
#   │ └─executions
#   │   └─operations
#   │     └─29aec796-ad19-4e6b-a83b-b8b9f55d0abb
#   │        └─123458 ${@}
baseCgroup=$(dirname "${cgroupNameRelativePath}")
# Bouncing my own PID $$ into /sys/fs/cgroup${baseCgroup}/$cgroupName"
echo $$ > "/sys/fs/cgroup${baseCgroup}/$cgroupName/cgroup.procs"

# Exec the rest of the arguments as-is
exec "$@"