{{- if .Values.shardWorker.autoscaling.enabled -}}
apiVersion: {{ include "buildfarm.autoscalingVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "buildfarm.fullname" . }}-shard-worker
  labels:
    name: {{ include "buildfarm.fullname" . }}-shard-worker
    {{- include "buildfarm.labels" . | nindent 4 }}
  {{- with .Values.shardWorker.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxReplicas: {{ .Values.shardWorker.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.shardWorker.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name:  {{ include "buildfarm.fullname" . }}-shard-worker
  {{- if contains "autoscaling/v2" (include "buildfarm.autoscalingVersion" . ) }}
    {{- if .Values.shardWorker.autoscaling.behavior }}
  behavior:
      {{- toYaml .Values.shardWorker.autoscaling.behavior | nindent 4 }}
    {{- end }}
  metrics:
    {{- toYaml .Values.shardWorker.autoscaling.metrics | nindent 4 }}
  {{- else }}
  targetCPUUtilizationPercentage: {{ .Values.shardWorker.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
