package(default_visibility = ["//visibility:public"])

filegroup(
    name = "example_configs",
    srcs = glob(["*.yml"]),
)

filegroup(
    name = "example_properties",
    srcs = glob(["*.properties"]),
    visibility = ["//visibility:public"],
)
