digestFunction: SHA256
defaultActionTimeout: 600
maximumActionTimeout: 3600
maxEntrySizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
prometheusPort: 9090
allowSymlinkTargetAbsolute: false
server: !include "server.yml"
backplane: !include "backplane.yml"
worker:
  publicName: localhost:8981
  executeStageWidth: 5
  limitGlobalExecution: true
  dequeueMatchSettings:
    allowUnmatched: true
  linkedInputDirectories:
  - (?!external/)[^/]+
  sandboxSettings:
    alwaysUseSandbox: true
    alwaysUseCgroups: true
    alwaysUseTmpFs: true
    tmpFsPaths: ["/tmp", "/dev/shm"]
    selectForBlockNetwork: true
    selectForTmpFs: true