name: Build and Push Base Buildfarm Worker Images

on:
  push:
    branches:
    - main
    paths:
    - ci/base-worker-image/jammy/Dockerfile
    - ci/base-worker-image/lunar/Dockerfile
    - ci/base-worker-image/noble/Dockerfile
permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Base Buildfarm Worker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1   # v4.4.0
        # QEMU needed for the ARM variant.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069   # v4.4.1
        # Docker Buildx needed for the ARM variant.

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f   # v4.6.0
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}


    - name: Build Jammy Docker image
        # AKA Ubuntu 22
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc   # v7.4.0
      with:
        context: .
        file: ./ci/base-worker-image/jammy/Dockerfile
        push: true
        tags: bazelbuild/buildfarm-worker-base:jammy

    - name: Build Lunar Docker image
        # AKA Ubuntu 23
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc   # v7.4.0
      with:
        context: .
        file: ./ci/base-worker-image/lunar/Dockerfile
        push: true
        tags: bazelbuild/buildfarm-worker-base:lunar

    - name: Build Multi-arch Noble Docker image
        # AKA Ubuntu 24
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc   # v7.4.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./ci/base-worker-image/noble/Dockerfile
        push: true
        tags: bazelbuild/buildfarm-worker-base:noble
