name: Build and Push Latest Buildfarm Images

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
    - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86   # 0.19.0
      with:
          # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2   # v4.0.0
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

    - name: Build Server Image
      id: buildAndPushServerImage
      run: bazel run //container:public_push_buildfarm-server -- --tag latest

    - name: Build Worker Image
      id: buildAndPushWorkerImage
      run: bazel run //container:public_push_buildfarm-worker -- --tag latest
