name: Build and Push Latest Buildfarm Images

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
    - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86   # 0.19.0
      with:
          # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10   # v6.0.3

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee   # v4.2.0
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

    - name: Build Server Image
      id: buildAndPushServerImage
      run: bazel run //container:public_push_buildfarm-server -- --tag latest

    - name: Build Worker Image
      id: buildAndPushWorkerImage
      run: bazel run //container:public_push_buildfarm-worker -- --tag latest
